version: "3"
services:
  app:
    container_name: react-app
    image: ardagon/react-shopping-cart
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /c/Users/shari/Documents/Projects/React/react-shopping-cart/app/react-app/src:/usr/app/react-app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
